term=foot
#term=foot
# rename to foot.ini and add your custom foot overrides hereafter
#term=foot-extra
resize-delay-ms=50
font=RobotoMono Nerd Font Mono:size=12
selection-target=clipboard
#initial-window-size-pixels=2000x1000
#dpi-aware=yes


[main]
include=~/.config/foot/themes/noctalia
shell=/run/current-system/sw/bin/fish
# pad=WIDTHxHEIGHT
# Adds at least WIDTH pixels left/right
# and HEIGHT pixels top/bottom inside the terminal
pad=10x20

# Client-side decoration hint:
# preferred = client | server | none
# Default is `server` (decorations drawn by compositor)
[csd]
preferred = none
size = 24

[scrollback]
lines=10000

[cursor]
# style=block
#color=141a1b eeeeee
[colors-dark]
alpha=0.9
#regular0=545454 # black
#cursor=141a1b eeeeee

[mouse-bindings]
#select-extend=none
#select-word=none
#select-begin=none
primary-paste=none
select-begin-block=none
select-extend-character-wise=none

clipboard-copy=Control+BTN_LEFT
clipboard-paste=Control+BTN_RIGHT


[key-bindings]
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v
